import assert from "node:assert/strict";
import test from "node:test";
import { compensationFor } from "./compensation";
import type { Internship } from "./types";

function fixtureJob(overrides: Partial<Internship> = {}): Internship {
  return {
    id: "fixture",
    tracking_key: "00000000-0000-4000-8000-000000000001",
    title: "Infrastructure Engineering Intern",
    company: "Example Labs",
    location: "Denver, CO",
    category: "cloud",
    role_type: "internship",
    season: "Summer 2027",
    term_keys: ["summer-2027"],
    salary: null,
    link: "https://example.com/jobs/fixture",
    source: "fixture",
    sponsorship: null,
    posted_date: "2026-07-10",
    first_seen_at: "2026-07-10T00:00:00Z",
    last_seen_at: "2026-07-10T00:00:00Z",
    last_checked_at: "2026-07-10T00:00:00Z",
    is_active: true,
    company_domain: null,
    country_code: "US",
    region_code: "CO",
    city: "Denver",
    metro_id: "denver",
    location_type: "onsite",
    normalization_confidence: 1,
    contributing_sources: ["fixture"],
    salary_currency: null,
    salary_minimum: null,
    salary_maximum: null,
    salary_cadence: null,
    annualized_salary_minimum: null,
    annualized_salary_maximum: null,
    salary_parse_confidence: null,
    salary_provenance: null,
    listing_changes: [],
    ...overrides,
  };
}

test("source-listed pay keeps the source value without claiming verification", () => {
  const compensation = compensationFor(
    fixtureJob({ salary: "  $42/hr  " }),
  );

  assert.equal(compensation.label, "$42/hr");
  assert.equal(compensation.kind, "source-listed");
  assert.equal(compensation.estimated, false);
  assert.equal(
    compensation.disclosure,
    "Pay shown in the source listing; verify details before applying",
  );
  assert.equal(compensation.title, compensation.disclosure);
  assert.doesNotMatch(compensation.disclosure, /verified|employer.reported/i);
});

test("missing pay is explicitly marked as a broad category estimate", () => {
  const internship = compensationFor(fixtureJob());
  const newGrad = compensationFor(
    fixtureJob({ role_type: "new_grad", category: "software" }),
  );

  assert.equal(internship.label, "Est. $30–50/hr");
  assert.equal(internship.kind, "category-estimate");
  assert.equal(internship.estimated, true);
  assert.match(internship.disclosure, /generated by this site/i);
  assert.match(internship.disclosure, /not supplied by the source listing/i);
  assert.equal(newGrad.label, "Est. $95–145k/yr");
  assert.equal(newGrad.kind, "category-estimate");
});
