import assert from "node:assert/strict";
import test from "node:test";
import { compensationFor } from "./compensation";
import type { Internship } from "./types";

function fixtureJob(overrides: Partial<Internship> = {}): Internship {
  return {
    id: "fixture",
    title: "Infrastructure Engineering Intern",
    company: "Example Labs",
    location: "Denver, CO",
    category: "cloud",
    role_type: "internship",
    season: "Summer 2027",
    salary: null,
    link: "https://example.com/jobs/fixture",
    source: "fixture",
    sponsorship: null,
    posted_date: "2026-07-10",
    first_seen_at: "2026-07-10T00:00:00Z",
    last_seen_at: "2026-07-10T00:00:00Z",
    is_active: true,
    ...overrides,
  };
}

test("employer-listed pay keeps the supplied value and requires destination confirmation", () => {
  const compensation = compensationFor(
    fixtureJob({ salary: "  $42/hr  " }),
  );

  assert.equal(compensation.label, "$42/hr");
  assert.equal(compensation.kind, "source-listed");
  assert.equal(compensation.estimated, false);
  assert.equal(
    compensation.disclosure,
    "Pay was explicitly included with the upstream listing and is stored as employer-listed evidence; confirm the current amount and terms on the application page",
  );
  assert.equal(compensation.title, compensation.disclosure);
  assert.match(compensation.disclosure, /confirm/i);
});

test("missing pay is explicitly marked as a broad category estimate", () => {
  const internship = compensationFor(fixtureJob());
  const newGrad = compensationFor(
    fixtureJob({ role_type: "new_grad", category: "software" }),
  );

  assert.equal(internship.label, "Est. $30–50/hr");
  assert.equal(internship.kind, "category-estimate");
  assert.equal(internship.estimated, true);
  assert.match(internship.disclosure, /generated by this site/i);
  assert.match(internship.disclosure, /not supplied by the source listing/i);
  assert.equal(newGrad.label, "Est. $95–145k/yr");
  assert.equal(newGrad.kind, "category-estimate");
});
