import type { Category, Internship, RoleType } from "@/lib/types";

type PayRangeByRole = Record<RoleType, readonly [number, number]>;

const ESTIMATED_PAY_RANGES: Record<Category, PayRangeByRole> = {
  software: { internship: [28, 48], new_grad: [95, 145] },
  cloud: { internship: [30, 50], new_grad: [100, 150] },
  "data-ml": { internship: [30, 52], new_grad: [100, 155] },
  quant: { internship: [45, 80], new_grad: [125, 210] },
  security: { internship: [27, 46], new_grad: [90, 140] },
  hardware: { internship: [27, 45], new_grad: [88, 135] },
  mechanical: { internship: [23, 36], new_grad: [72, 105] },
  electrical: { internship: [24, 40], new_grad: [78, 118] },
  civil: { internship: [21, 32], new_grad: [65, 95] },
  aerospace: { internship: [24, 40], new_grad: [78, 120] },
  manufacturing: { internship: [22, 34], new_grad: [68, 100] },
  industrial: { internship: [22, 35], new_grad: [70, 105] },
  materials: { internship: [22, 36], new_grad: [70, 108] },
  finance: { internship: [24, 42], new_grad: [70, 115] },
  consulting: { internship: [25, 42], new_grad: [75, 120] },
  accounting: { internship: [20, 32], new_grad: [60, 90] },
  operations: { internship: [20, 33], new_grad: [62, 95] },
  product: { internship: [25, 45], new_grad: [85, 130] },
  marketing: { internship: [18, 30], new_grad: [55, 85] },
  "supply-chain": { internship: [20, 32], new_grad: [62, 92] },
  other: { internship: [20, 35], new_grad: [65, 105] },
};

export interface Compensation {
  label: string;
  kind: "source-listed" | "category-estimate";
  estimated: boolean;
  disclosure: string;
  title: string;
}

export function compensationFor(job: Internship): Compensation {
  const reported = job.salary?.trim();
  if (reported) {
    const disclosure =
      "Pay was explicitly included with the upstream listing and is stored as employer-listed evidence; confirm the current amount and terms on the application page";
    return {
      label: reported,
      kind: "source-listed",
      estimated: false,
      disclosure,
      title: disclosure,
    };
  }

  const [low, high] = ESTIMATED_PAY_RANGES[job.category][job.role_type];
  const disclosure =
    "Broad US category estimate generated by this site, not supplied by the source listing; actual pay varies by role and location";
  return {
    label:
      job.role_type === "internship"
        ? `Est. $${low}\u2013${high}/hr`
        : `Est. $${low}\u2013${high}k/yr`,
    kind: "category-estimate",
    estimated: true,
    disclosure,
    title: disclosure,
  };
}

function annualizePay(
  amount: number,
  thousands: boolean,
  rawUnit: string | undefined,
): number {
  const value = amount * (thousands ? 1000 : 1);
  const unit = rawUnit?.toLowerCase();

  if (unit?.startsWith("hr") || unit?.startsWith("hour")) {
    return value * 2080;
  }
  if (unit?.startsWith("mo") || unit?.startsWith("month")) {
    return value * 12;
  }
  if (unit?.startsWith("yr") || unit?.startsWith("year")) return value;

  // A bare value is only unambiguous when it is already annual-sized or uses
  // a "k" suffix. "$42" could be hourly, monthly, or a typo, so keep it out.
  return thousands || value >= 1000 ? value : 0;
}

/**
 * Employer-listed pay -> approximate annual USD. For ranges, this deliberately
 * returns the lower bound so a minimum-pay filter never qualifies a listing
 * only because the top of its advertised range clears the threshold.
 */
export function annualSalary(salary: string | null): number {
  if (!salary) return 0;
  const normalized = salary.replace(/,/g, "");
  const unit = "(hr|hour|hourly|yr|year|yearly|mo|month|monthly)s?";
  const rangePattern = new RegExp(
    `(\\$)?\\s*(\\d+(?:\\.\\d+)?)\\s*(k)?\\s*(?:(?:\\/|per\\s+)\\s*${unit})?\\s*(?:[-\\u2012-\\u2015]|to)\\s*(\\$)?\\s*(\\d+(?:\\.\\d+)?)\\s*(k)?\\s*(?:(?:\\/|per\\s+)\\s*${unit})?`,
    "gi",
  );

  for (const match of normalized.matchAll(rangePattern)) {
    const hasPayMarker = Boolean(
      match[1] || match[3] || match[4] || match[5] || match[7] || match[8],
    );
    if (!hasPayMarker) continue;

    const lowUnit = match[4] ?? match[8];
    const lowThousands = Boolean(match[3] || (!match[4] && match[7]));
    return annualizePay(Number(match[2]), lowThousands, lowUnit);
  }

  const scalarPattern = new RegExp(
    `(\\$)?\\s*(\\d+(?:\\.\\d+)?)\\s*(k)?\\s*(?:(?:\\/|per\\s+)\\s*${unit})?`,
    "gi",
  );
  for (const match of normalized.matchAll(scalarPattern)) {
    if (!match[1] && !match[3] && !match[4]) continue;
    return annualizePay(Number(match[2]), Boolean(match[3]), match[4]);
  }

  return 0;
}
