import { writeFile } from "node:fs/promises";
import path from "node:path";
import { ingestArtifactChecksum } from "./ingest-artifact";

async function main(): Promise<void> {
  const checksum = await ingestArtifactChecksum();
  const output = `/** Generated by npm run ingest:artifact:generate. */\n` +
    `export const INGEST_SOURCE_CHECKSUM = ${JSON.stringify(checksum)};\n`;

  await writeFile(
    path.join(process.cwd(), "supabase/functions/ingest/manifest.ts"),
    output,
    "utf8",
  );
  console.log(checksum);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
