create table if not exists public.ingest_source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  succeeded boolean not null,
  complete_snapshot boolean not null default false,
  fetched_count integer not null default 0 check (fetched_count >= 0),
  accepted_count integer not null default 0 check (accepted_count >= 0),
  error text,
  ran_at timestamptz not null default now()
);

alter table public.ingest_source_runs enable row level security;

create index if not exists ingest_source_runs_source_ran_at_idx
  on public.ingest_source_runs (source, ran_at desc);

create or replace function public.ingest_upsert_v2(
  payload jsonb,
  secret text,
  source_results jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  expected text;
  ins_count integer := 0;
  upd_count integer := 0;
  deact_count integer := 0;
begin
  select value->>'secret'
    into expected
    from public.app_meta
    where key = 'cron_secret';

  if expected is null or secret is distinct from expected then
    raise exception 'unauthorized';
  end if;

  if jsonb_typeof(payload) <> 'array' or jsonb_typeof(source_results) <> 'array' then
    raise exception 'payload and source_results must be JSON arrays';
  end if;

  insert into public.ingest_source_runs (
    source,
    succeeded,
    complete_snapshot,
    fetched_count,
    accepted_count,
    error
  )
  select distinct on (source)
    source,
    coalesce(succeeded, false),
    coalesce(complete_snapshot, false),
    greatest(coalesce(fetched, 0), 0),
    greatest(coalesce(accepted, 0), 0),
    nullif(error, '')
  from jsonb_to_recordset(source_results) as result(
    source text,
    fetched integer,
    accepted integer,
    succeeded boolean,
    complete_snapshot boolean,
    error text
  )
  where source is not null and source <> ''
  order by source;

  with rows as (
    select distinct on (row_data.dedupe_key) row_data.*
    from jsonb_to_recordset(payload) as row_data(
      title text,
      company text,
      location text,
      category text,
      role_type text,
      season text,
      salary text,
      link text,
      source text,
      sponsorship text,
      posted_date date,
      dedupe_key text,
      company_domain text
    )
    where row_data.dedupe_key is not null
      and row_data.title is not null
      and row_data.company is not null
      and row_data.link is not null
      and row_data.source is not null
  ),
  upserted as (
    insert into public.internships (
      title,
      company,
      location,
      category,
      role_type,
      season,
      salary,
      link,
      source,
      sponsorship,
      posted_date,
      dedupe_key,
      company_domain
    )
    select
      title,
      company,
      coalesce(location, ''),
      coalesce(category, 'other'),
      coalesce(role_type, 'internship'),
      season,
      salary,
      link,
      source,
      sponsorship,
      posted_date,
      dedupe_key,
      company_domain
    from rows
    on conflict (dedupe_key) do update set
      title = excluded.title,
      company = excluded.company,
      location = excluded.location,
      category = excluded.category,
      role_type = excluded.role_type,
      season = coalesce(excluded.season, public.internships.season),
      salary = coalesce(excluded.salary, public.internships.salary),
      link = excluded.link,
      sponsorship = coalesce(excluded.sponsorship, public.internships.sponsorship),
      posted_date = coalesce(public.internships.posted_date, excluded.posted_date),
      company_domain = coalesce(excluded.company_domain, public.internships.company_domain),
      last_seen_at = now(),
      is_active = true
    returning (xmax = 0) as is_insert
  )
  select
    count(*) filter (where is_insert),
    count(*) filter (where not is_insert)
  into ins_count, upd_count
  from upserted;

  with complete_sources as (
    select distinct source
    from jsonb_to_recordset(source_results) as result(
      source text,
      fetched integer,
      accepted integer,
      succeeded boolean,
      complete_snapshot boolean,
      error text
    )
    where source is not null
      and succeeded is true
      and complete_snapshot is true
      and coalesce(fetched, 0) > 0
  ),
  batch_keys as (
    select row_data->>'dedupe_key' as dedupe_key
    from jsonb_array_elements(payload) as row_data
    where row_data->>'dedupe_key' is not null
  ),
  deactivated as (
    update public.internships internship
    set is_active = false, last_seen_at = now()
    where internship.is_active
      and internship.source in (select source from complete_sources)
      and not exists (
        select 1
        from batch_keys
        where batch_keys.dedupe_key = internship.dedupe_key
      )
    returning 1
  )
  select count(*) into deact_count from deactivated;

  return jsonb_build_object(
    'inserted', ins_count,
    'updated', upd_count,
    'deactivated', deact_count
  );
end;
$function$;